[package]
name = "constellation_bot"
version = "0.1.0"
authors = ["Betsy Haibel <betsy.haibel@gmail.com>"]

[dependencies]
libc = "0.2.0"
rand = "0.3"
svg = "0.5.1"
num = "0.1"

[lib]
name = "constellation"
crate-type = ["dylib"]